// Interpreter object - validates the user input

// Internal command data generated by this module:
// Place will be of the form [X, Y, F]
// Other valid commands will be passed through as is

function Interpreter() {
  }

Interpreter.prototype.process = function(input_data) {
    if (input_data.match(/PLACE [0-4],[0-4],(NORTH|EAST|SOUTH|WEST)/g)) {
        return [parseInt(input_data[6]), parseInt(input_data[8]), input_data.split(',').pop().slice(0, -1)]
    } else if (input_data === 'MOVE\n') {
        return 'MOVE';
    } else if (input_data === 'LEFT\n') {
        return 'LEFT';
    } else if (input_data === 'RIGHT\n') {
        return 'RIGHT';
    } else if (input_data === 'REPORT\n') {
        return 'REPORT';
    } else {
        return 'INVALID';
    }
};

module.exports = {
    Interpreter: Interpreter
}
